# Generated by Django 3.2 on 2022-04-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=11)),
                ('message', models.TextField(default='')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
