# Generated by Django 3.2 on 2022-04-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_country_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.country'),
            preserve_default=False,
        ),
    ]
